const { verifyAppiumSession } = require('./helpers');
const { APP_PACKAGE, APP_ACTIVITY } = require('./constants');

/**
 * Returns detailed parameterized test definitions for all 10 categories.
 */
function getCategoryTestDefinitions() {
  const categories = [
    {
      name: 'Authentication',
      prefix: 'AUTH',
      actions: [
        'Validate Login Driver Session & App Package',
        'Verify Email Input Field Presence and Accessibility',
        'Verify Password Masking and Toggle Eye Icon',
        'Submit Valid Login Credentials',
        'Submit Empty Credentials & Assert Error Message',
        'Submit Invalid Email Format & Verify Validation Alert',
        'Submit Incorrect Password & Verify Auth Failure Dialog',
        'Verify Forgot Password Link Navigation',
        'Verify Reset Password Email Prompt',
        'Verify Remember Me Checkbox Selection State',
        'Verify Google OAuth Single Sign-On Button',
        'Verify Fingerprint / Biometric Login Option',
        'Verify Registration Screen Transition',
        'Verify Full Name Input Field Validation',
        'Verify Phone Number Country Code Selector',
        'Verify Terms of Service Link Interaction',
        'Verify Privacy Policy Link Interaction',
        'Verify OTP Code Input Matrix Verification',
        'Verify Resend OTP Countdown Timer',
        'Verify Password Strength Indicator Bar',
        'Verify Login Session Token Storage',
        'Verify Logout Navigation & Token Invalidation',
        'Verify Auto-Login with Active Refresh Token',
        'Verify Concurrent Login Multi-Device Session Alert',
        'Verify Password Expiration Policy Prompt',
        'Verify Account Lockout After 5 Failed Attempts',
        'Verify Captcha Verification Challenge Rendering',
        'Verify Security Questions Setup Screen',
        'Verify Two-Factor Authentication Setup Switch',
        'Verify Back Button Navigation from Login',
        'Verify Dark Mode Auth Screen Rendering',
        'Verify Screen Orientation Change on Auth Page',
        'Verify Soft Keyboard Hide on Tap Outside',
        'Verify IME Done Key Submission Behavior',
        'Verify Login Screen UI Layout Constraints',
        'Verify Auth State Persistence Across App Re-launch',
        'Verify Network Offline Banner on Login Screen',
        'Verify Timeout Exception Recovery on Authentication',
        'Verify Deep Link Login Action Handling',
        'Verify Cross-Site Scripting Input Sanitization',
        'Verify SQL Injection Protection in Auth Fields',
        'Verify Maximum Character Length in Password Input',
        'Verify Special Character Handling in User Inputs',
        'Verify Auth Splash Screen Animation Completion',
        'Verify Auth Error Banner Dismissal',
        'Verify Session Inactivity Auto Lock',
        'Verify Multi-Tenant Organization Switcher',
        'Verify SSO SAML Provider Selection',
        'Verify Guest Login Access Restrictions',
        'Verify Auth End-to-End Flow Validation'
      ]
    },
    {
      name: 'Dashboard',
      prefix: 'DASH',
      actions: [
        'Validate Dashboard Session, Contexts & Activity',
        'Verify Dashboard Header Greeting User Name',
        'Verify Quick Health Metrics Cards Rendered',
        'Verify Heart Rate Metric Card Dynamic Update',
        'Verify Blood Pressure Metric Card Display',
        'Verify Blood Sugar Level Metric Card Visual',
        'Verify BMI Metric Calculator Widget',
        'Verify Daily Step Count Graph Render',
        'Verify Calories Burned Progress Bar',
        'Verify Sleep Tracker Summary Card',
        'Verify Water Intake Log Button Action',
        'Verify Add New Health Record Floating Action Button',
        'Verify Upcoming Doctor Appointment Widget',
        'Verify Medication Reminder Alert Card',
        'Verify Recent Medical Activity Log List',
        'Verify Emergency SOS Button Visibility',
        'Verify Emergency Contact Dial Action',
        'Verify Dashboard Swipe-to-Refresh Gesture',
        'Verify Dashboard Pull-Down Sync Indicator',
        'Verify Dashboard Dark Mode Visual Contrast',
        'Verify Dashboard Multi-Language Switch',
        'Verify Dashboard Notification Bell Badge Count',
        'Verify Dashboard Navigation Drawer Toggle',
        'Verify Dashboard Search Bar Focus Behavior',
        'Verify Dashboard Filter Chips Interaction',
        'Verify Dashboard Weather/Pollen Index Widget',
        'Verify Dashboard Offline Cached Data View',
        'Verify Dashboard Skeleton Loading State',
        'Verify Dashboard Scroll Performance',
        'Verify Dashboard Grid View Rearrange Drag Gesture',
        'Verify Dashboard Metric Detail Tap Navigation',
        'Verify Dashboard Quick Share Report Action',
        'Verify Dashboard Doctor Consultation Banner',
        'Verify Dashboard Health Tip of the Day Slide',
        'Verify Dashboard Sync Status Cloud Icon',
        'Verify Dashboard Battery Optimization Alert',
        'Verify Dashboard Accessibility Content Descriptions',
        'Verify Dashboard Text Size Dynamic Scaling',
        'Verify Dashboard Layout Orientation Change',
        'Verify Dashboard Memory Usage Profile Check',
        'Verify Dashboard API Error Retry Button',
        'Verify Dashboard User Avatar Thumbnail Render',
        'Verify Dashboard Target Goals Achievement Popup',
        'Verify Dashboard Daily Check-in Streak Badge',
        'Verify Dashboard Vital Signs Trend Chart',
        'Verify Dashboard Export PDF Quick Action',
        'Verify Dashboard Connected Wearable Device Status',
        'Verify Dashboard Sync Now Button Throttle',
        'Verify Dashboard Empty State Placeholder',
        'Verify Dashboard Full End-to-End Render Check'
      ]
    },
    {
      name: 'Health Records',
      prefix: 'REC',
      actions: [
        'Validate Health Records Appium Session & Activity',
        'Verify Medical History List Items Display',
        'Verify Add New Medical Record Form Display',
        'Verify Record Title Text Input Validation',
        'Verify Record Category Dropdown Selection',
        'Verify Record Date Picker Dialog Interaction',
        'Verify Record Time Picker Dialog Interaction',
        'Verify Record Doctor Name Input Field',
        'Verify Record Hospital / Clinic Name Input',
        'Verify Record Notes Multi-Line Text Area',
        'Verify Attachment File Selector Button',
        'Verify Camera Capture Medical Document Action',
        'Verify Record Save Action Button Enabled State',
        'Verify Record Creation Success Toast Notice',
        'Verify Record Detail View Navigation',
        'Verify Record Edit Action Form Populated',
        'Verify Record Update Success Confirmation',
        'Verify Record Delete Confirmation Dialog',
        'Verify Record Delete Action List Update',
        'Verify Record Search Filter by Keywords',
        'Verify Record Filter by Date Range Picker',
        'Verify Record Filter by Medical Category',
        'Verify Record Sorting by Date Ascending',
        'Verify Record Sorting by Date Descending',
        'Verify Record Export to PDF Action',
        'Verify Record Share via Email Action',
        'Verify Record Print Document Action',
        'Verify Record Encryption Tag Indicator',
        'Verify Record Offline Creation Queueing',
        'Verify Record Sync Status Indicator',
        'Verify Record Duplicate Prevention Alert',
        'Verify Record Tagging & Tag Filter Pills',
        'Verify Record Favorite Star Toggle State',
        'Verify Record Archival Folder Navigation',
        'Verify Record Restore Archived Item',
        'Verify Record Image Preview Zoom & Pan',
        'Verify Record Audio Note Recording Button',
        'Verify Record Audio Playback Controls',
        'Verify Record Pagination Load More Items',
        'Verify Record Infinite Scroll List Loader',
        'Verify Record Bulk Selection Mode Toggle',
        'Verify Record Bulk Delete Action Warning',
        'Verify Record Bulk Export Zip File Creation',
        'Verify Record Privacy Lock Access PIN Prompt',
        'Verify Record Doctor Access Share QR Code',
        'Verify Record Import External FHIR Data',
        'Verify Record Audit Trail History Timeline',
        'Verify Record Field Input Sanitization',
        'Verify Record Memory Footprint on Large List',
        'Verify Health Records Complete Lifecycle Test'
      ]
    },
    {
      name: 'Diagnosis Reports',
      prefix: 'DIAG',
      actions: [
        'Validate Diagnosis Reports Appium Session & Package',
        'Verify Diagnostic Reports List View Rendering',
        'Verify Lab Test Results Details View',
        'Verify Blood Test Parameter Table Values',
        'Verify Abnormal Value Highlighting in Red',
        'Verify Normal Value Range Gauge Indicators',
        'Verify Radiology Image Scanner View',
        'Verify DICOM Image Viewer Controls',
        'Verify Pathology Report Summary Text',
        'Verify Genetic Test Result Disclaimer Banner',
        'Verify Doctor Digital Signature Verification',
        'Verify Lab Location & Contact Information',
        'Verify Diagnostic Report PDF Download Progress',
        'Verify PDF Viewer Zoom & Page Scroll',
        'Verify Report Share with Primary Care Doctor',
        'Verify Report Trend Analysis Line Graph',
        'Verify Cholesterol Level Multi-Year Comparison',
        'Verify Blood Sugar HbA1c Historical Chart',
        'Verify Diagnostic Report Search Bar Filter',
        'Verify Filter Reports by Diagnostic Lab Name',
        'Verify Filter Reports by Pending vs Completed',
        'Verify Report Request New Test Order Button',
        'Verify Diagnostic Center Map Location Pin',
        'Verify Report Appointment Scheduling Link',
        'Verify Critical Result Immediate Notification Popup',
        'Verify Second Opinion Request Action',
        'Verify Report Confidentiality Lock Toggle',
        'Verify OCR Text Extraction from Uploaded Lab Sheet',
        'Verify AI Diagnostic Summary Suggestion Card',
        'Verify Report Comparative Analytics Engine',
        'Verify Report Printing Spooler Handshake',
        'Verify Medical Glossary Term Tooltip Tap',
        'Verify Diagnostic Metric Unit Converter',
        'Verify Doctor Prescription Link to Diagnosis',
        'Verify Pending Lab Result Status Bar',
        'Verify Diagnostic Test Preparation Instructions View',
        'Verify Diagnostic Cost Estimate Breakdown Card',
        'Verify Insurance Pre-Authorization Status Indicator',
        'Verify Report Download Cache Clearance',
        'Verify Diagnostic Report Watermark Verification',
        'Verify Report Export to Apple Health / Google Fit',
        'Verify Report Annotation Markup Tools',
        'Verify Diagnostic Report Voice Reader Accessibility',
        'Verify Report Timestamp Timezone Conversion',
        'Verify Report Archival Retention Schedule Alert',
        'Verify Invalid Report Payload Error Boundary',
        'Verify Diagnostic Network Disconnection Handling',
        'Verify Diagnostic Report Print Preview Layout',
        'Verify Diagnostic Report Bulk Archive Action',
        'Verify Diagnosis Reports Complete Module Validation'
      ]
    },
    {
      name: 'Upload Documents',
      prefix: 'DOC',
      actions: [
        'Validate Upload Documents Appium Driver Session',
        'Verify Document Upload Screen Layout & Dropzone',
        'Verify File Picker Permission Dialog Handling',
        'Verify Select PDF Document File Option',
        'Verify Select JPEG/PNG Image File Option',
        'Verify Camera Document Scanner Mode Launch',
        'Verify Camera Auto Edge Detection Frame',
        'Verify Multi-Page Scan Capture Sequence',
        'Verify Document Crop & Rotate Controls',
        'Verify Document Contrast & Color Filter Picker',
        'Verify Upload File Size Exceeded Warning Alert',
        'Verify Unsupported File Extension Error Notice',
        'Verify Upload Progress Bar Real-Time Percentage',
        'Verify Cancel Upload Transfer Action Button',
        'Verify Upload Resume on Network Recovery',
        'Verify Cloud Upload Success Checkmark Animation',
        'Verify Auto Document Classification Tag',
        'Verify Manual Document Type Categorization Menu',
        'Verify Add Custom Document Notes & Tags',
        'Verify Document Security Encryption Badge',
        'Verify Document Password Protection Prompt',
        'Verify Uploaded Documents Grid Thumbnail Display',
        'Verify Document Delete Confirmation Popup',
        'Verify Replace Document File Action',
        'Verify Cloud Storage Quota Bar Display',
        'Verify Upload Queue Multi-File Batch Status',
        'Verify Background Document Upload Sync',
        'Verify OCR Automated Data Extraction Trigger',
        'Verify OCR Extracted Text Verification Card',
        'Verify Document Expiration Date Alert Setting',
        'Verify Document Access Permission Selector',
        'Verify Share Document Link Generator',
        'Verify Temporary Document Expiration Link Set',
        'Verify Download Stored Document Action',
        'Verify Offline Document Staging Folder',
        'Verify Duplicate File Hash Recognition Alert',
        'Verify Document Watermark Overlay Option',
        'Verify Document Metadata Properties Sheet',
        'Verify High-Res Image Compression Toggle',
        'Verify Document Search by OCR Extracted Text',
        'Verify Drag-and-Drop Batch Ordering Gesture',
        'Verify Upload Retry Policy on 500 Server Error',
        'Verify Document Upload Audit Log Timestamp',
        'Verify Cloud Provider Storage Switch (S3/Drive)',
        'Verify Document Thumbnail Loading Placeholder',
        'Verify Virus Scanning Status Indicator on File',
        'Verify Document Transfer Speed Calculation',
        'Verify Document File Signature Validation',
        'Verify Low Device Storage Space Warning',
        'Verify Upload Documents End-to-End Module Test'
      ]
    },
    {
      name: 'Profile',
      prefix: 'PROF',
      actions: [
        'Validate Profile Appium Session, Activity & Package',
        'Verify User Profile Header Details Display',
        'Verify Profile Picture Avatar Display',
        'Verify Profile Picture Upload / Change Action',
        'Verify Edit Personal Info Form Navigation',
        'Verify First & Last Name Input Validation',
        'Verify Date of Birth Picker Calendar Selection',
        'Verify Gender Selection Radio Button Group',
        'Verify Blood Group Dropdown Selector',
        'Verify Height Input Numeric Unit Toggle (cm/ft)',
        'Verify Weight Input Numeric Unit Toggle (kg/lbs)',
        'Verify Emergency Contact Information Form',
        'Verify Primary Care Physician Contact Card',
        'Verify Medical Insurance Provider Details Input',
        'Verify Policy Number & Group ID Fields',
        'Verify Allergies List Management & Addition',
        'Verify Chronic Conditions Multi-Select Chips',
        'Verify Current Medications List Display',
        'Verify Change Password Modal Action',
        'Verify Current Password Re-Verification',
        'Verify New Password Complexity Check',
        'Verify Save Profile Changes Button Action',
        'Verify Profile Update Success Toast Alert',
        'Verify Account Security Settings Toggle',
        'Verify Biometric Authentication Switch State',
        'Verify Push Notification Preferences Toggles',
        'Verify Email Digest Notification Frequency',
        'Verify App Theme Selector (Dark/Light/System)',
        'Verify Language Switcher Selection Dropdown',
        'Verify Data Privacy Controls & Export My Data',
        'Verify Delete Account Confirmation Warning',
        'Verify Connected Apps & Devices Permissions',
        'Verify Google Fit / Apple Health Sync Toggle',
        'Verify Profile Completeness Percentage Bar',
        'Verify Subscription Plan Status & Upgrade Badge',
        'Verify Terms of Service Link from Profile',
        'Verify Privacy Policy Link from Profile',
        'Verify App Version Information Footer Label',
        'Verify Help Center & FAQ Navigation Button',
        'Verify Support Ticket Submission Form',
        'Verify Send App Feedback Rating Stars',
        'Verify Logout Confirmation Dialog Actions',
        'Verify Clear App Cache & Temp Files Action',
        'Verify Profile Offline Mode Data Readability',
        'Verify Profile Image Crop Wheel Touch Gesture',
        'Verify Address Line 1 & Line 2 Input Fields',
        'Verify Zip Code Format Input Validation',
        'Verify State & Country Dropdown Dependencies',
        'Verify Profile Input XSS Sanitization Filter',
        'Verify Profile Module Complete Validation Test'
      ]
    },
    {
      name: 'Notifications',
      prefix: 'NOTIF',
      actions: [
        'Validate Notifications Appium Session & Contexts',
        'Verify Notification Center List Items Rendering',
        'Verify Unread Notification Badge Count Display',
        'Verify Medication Reminder Notification Alert',
        'Verify Appointment Confirmation Push Notice',
        'Verify Lab Result Ready System Notification',
        'Verify Doctor Message Chat Alert Card',
        'Verify Daily Health Tip Push Notification',
        'Verify Emergency Health Alert Banner Rendering',
        'Verify Notification Swipe-to-Dismiss Gesture',
        'Verify Clear All Notifications Action Button',
        'Verify Mark All as Read Toggle State',
        'Verify Notification Category Filter Chips',
        'Verify Filter by Reminders vs System Alerts',
        'Verify Tap Notification Deep Link Navigation',
        'Verify Notification Time Format Timestamp',
        'Verify Notification Settings Gear Icon Click',
        'Verify Quiet Hours / Do Not Disturb Schedule',
        'Verify Custom Notification Sound Selector',
        'Verify Vibration Pattern Toggle Selection',
        'Verify Lock Screen Notification Visibility Switch',
        'Verify In-App Banner Pop-up Rendering',
        'Verify In-App Alert Sound Volume Feedback',
        'Verify Scheduled Medication Alarm Trigger',
        'Verify Snooze Medication Reminder Action',
        'Verify Confirm Taken Medication Checkbox',
        'Verify Refill Prescription Alert Counter',
        'Verify Vaccine Due Notification Alert Card',
        'Verify Doctor Consultation 15-Min Reminder',
        'Verify Sync Notification Delivery Status',
        'Verify Offline Notification Local Queueing',
        'Verify Rich Push Notification Image Preview',
        'Verify Notification Action Button Interaction',
        'Verify Firebase Cloud Messaging Push Handler',
        'Verify Notification Payload Data Parser',
        'Verify Priority Notification Sound Override',
        'Verify Notification History Archival Search',
        'Verify Notification Permission Dialog Grant',
        'Verify Notification Permission Revocation Guard',
        'Verify Multi-User Notification Isolation',
        'Verify Repeated Notification Throttling Filter',
        'Verify Notification LED Color Flashing Sync',
        'Verify Wearable Watch Notification Mirroring',
        'Verify Notification Content Text Auto-Truncate',
        'Verify Notification Expandable Detail View',
        'Verify Notification Quick Reply Action Input',
        'Verify Notification Audit Timestamp Log',
        'Verify System Notification Channel Switch',
        'Verify Notification Mute Channel Option',
        'Verify Notifications Module Complete Test'
      ]
    },
    {
      name: 'API Integration',
      prefix: 'API',
      actions: [
        'Validate API Module Session, Activity & Package',
        'Verify REST Backend Base URL Reachability',
        'Verify Authentication Endpoint POST /api/login',
        'Verify JWT Auth Bearer Token Header Injection',
        'Verify Refresh Token POST /api/auth/refresh',
        'Verify Fetch Patient Profile GET /api/patient',
        'Verify Update Patient Profile PUT /api/patient',
        'Verify Fetch Health Records GET /api/records',
        'Verify Create Health Record POST /api/records',
        'Verify Update Health Record PUT /api/records/:id',
        'Verify Delete Health Record DELETE /api/records/:id',
        'Verify Upload Document Multipart POST /api/upload',
        'Verify Fetch Lab Reports GET /api/reports',
        'Verify Download Report PDF GET /api/reports/:id/pdf',
        'Verify OCR Processing Endpoint POST /api/ocr',
        'Verify AI Diagnosis Insights POST /api/ai/predict',
        'Verify Fetch Medication Reminders GET /api/reminders',
        'Verify Create Medication Alarm POST /api/reminders',
        'Verify Notification Device Token POST /api/fcm',
        'Verify Doctor Appointment List GET /api/appointments',
        'Verify Book Appointment POST /api/appointments',
        'Verify Cancel Appointment DELETE /api/appointments/:id',
        'Verify Emergency Contacts GET /api/emergency',
        'Verify API HTTP 200 OK Response Handling',
        'Verify API HTTP 400 Bad Request Error Parsing',
        'Verify API HTTP 401 Unauthorized Session Expiry',
        'Verify API HTTP 403 Forbidden Access Guard',
        'Verify API HTTP 404 Not Found Handling',
        'Verify API HTTP 409 Conflict Duplicate Error',
        'Verify API HTTP 429 Rate Limit Retry-After',
        'Verify API HTTP 500 Server Error Toast Alert',
        'Verify API HTTP 503 Gateway Unavailable Notice',
        'Verify Network Timeout Interceptor Retry Logic',
        'Verify Response JSON Schema Structure Validation',
        'Verify GZIP Compression Header Decoding',
        'Verify SSL Pinning Handshake Verification',
        'Verify CORS Pre-Flight Option Response',
        'Verify Request Retry Backoff Exponential Delay',
        'Verify Offline Request Queueing in Room DB',
        'Verify Background Sync Manager API Dispatch',
        'Verify Payload Encryption Data Cipher',
        'Verify API Response Caching ETag Header',
        'Verify GraphQL Query Query Patient Dashboard',
        'Verify WebSocket Real-Time Alert Channel',
        'Verify Mock API Endpoint Fallback Switch',
        'Verify Latency Benchmark Under 200ms Target',
        'Verify API Error Stack Trace Masking Security',
        'Verify Concurrent API Request Stress Test',
        'Verify API Token Expiration Auto-Logout',
        'Verify API Integration Complete Module Suite'
      ]
    },
    {
      name: 'Performance',
      prefix: 'PERF',
      actions: [
        'Validate Performance Appium Driver Session & Package',
        'Verify Application Cold Start Launch Time (<1.5s)',
        'Verify Application Warm Start Launch Time (<500ms)',
        'Verify App Startup Memory RSS Footprint (<120MB)',
        'Verify CPU Consumption Spikes During Navigation',
        'Verify GPU Frame Rendering Rate Target 60 FPS',
        'Verify UI Jank & Dropped Frames Benchmarks',
        'Verify Dashboard Screen Render Time (<300ms)',
        'Verify Health Records List Scroll FPS Smoothness',
        'Verify Large Dataset RecyclerView Scrolling',
        'Verify Image Caching Memory Allocations',
        'Verify Garbage Collection Pause Interruptions',
        'Verify File Upload Network Throughput Speed',
        'Verify PDF Report Generation Time Under 2s',
        'Verify OCR Text Extraction Processing Time',
        'Verify AI Inference Execution Speed Check',
        'Verify Background Battery Drain Measurement',
        'Verify CPU Wakelock Retention Duration Guard',
        'Verify Thermal Throttling App Temperature Impact',
        'Verify Network Bandwidth Efficiency Benchmark',
        'Verify Data Cache Read/Write Latency Benchmark',
        'Verify Room Database Query Execution Speed',
        'Verify Shared Preferences Retrieval Delay',
        'Verify Thread Pool Worker Task Queue Latency',
        'Verify APK Binary Footprint & DEX Size',
        'Verify Memory Leak Search After 50 Screen Navs',
        'Verify Screen Transition Animation Smoothness',
        'Verify Dialog Opening Delay Under 50ms Target',
        'Verify Keyboard Popup Layout Shift Delay',
        'Verify Camera Scanner Initial Frame Launch',
        'Verify Image Downscaling Compression Overhead',
        'Verify Biometric Authentication Latency (<300ms)',
        'Verify Push Notification Reception Speed',
        'Verify Disk I/O Write Performance During Sync',
        'Verify Memory Consumption on High-Res Photo Upload',
        'Verify Low-Memory Device Heap Pressure Recovery',
        'Verify App Behavior Under Low Battery (10%)',
        'Verify App Behavior Under Battery Saver Mode',
        'Verify Multi-Threading Deadlock Guard Checks',
        'Verify Application Crash Rate Under 0.01%',
        'Verify ANR (Application Not Responding) Prevention',
        'Verify Network Transition WiFi to Cellular Speed',
        'Verify Offline DB Write Batch Throughput',
        'Verify JSON Parsing Benchmark for 1000 Records',
        'Verify Background Service Idle Cpu Usage',
        'Verify UI Layout Hierarchy Nesting Depth Check',
        'Verify Asset Compression Factor Verification',
        'Verify Memory De-allocation on Activity Destroy',
        'Verify Memory Footprint Stability After 10 Min',
        'Verify Performance Module Complete Benchmark'
      ]
    },
    {
      name: 'Regression',
      prefix: 'REG',
      actions: [
        'Validate Regression Suite Session & Activity',
        'Verify Full User Registration to Dashboard Flow',
        'Verify Login with Saved Credentials Workflow',
        'Verify Create Health Record & Add PDF Attachment',
        'Verify Edit Health Record & Save Changes',
        'Verify Delete Health Record & List Refresh',
        'Verify Upload Diagnostic Report & OCR Processing',
        'Verify View Diagnostic Report Details & Trend Chart',
        'Verify Set Medication Reminder & Receive Alert',
        'Verify Update Profile Information & Save',
        'Verify Change Password & Re-login Sequence',
        'Verify Switch Theme to Dark Mode & Verify Layout',
        'Verify Change App Language to Spanish / French',
        'Verify Network Disconnect & Offline Record Draft',
        'Verify Network Reconnect & Auto Background Sync',
        'Verify Export Medical Records to PDF Document',
        'Verify Share Medical Report via Email Intent',
        'Verify Emergency SOS Button & Dial Action',
        'Verify Search Health Records with Complex Terms',
        'Verify Filter Records by Date Range & Category',
        'Verify Notification Center Clear All Items Flow',
        'Verify Doctor Appointment Booking Workflow',
        'Verify Doctor Appointment Cancellation Workflow',
        'Verify Change Biometric Login Preference Setting',
        'Verify Clear App Cache & Re-Initialize Data',
        'Verify App Background & Resume State Recovery',
        'Verify Device Rotation Orientation Consistency',
        'Verify App Killed in Background State Restore',
        'Verify Multi-Device Sync Data Consistency',
        'Verify Security Pin Lock Timeout & Challenge',
        'Verify Back Button Stack History Navigation',
        'Verify Deep Link Opening Specific Record View',
        'Verify Terms & Privacy Document Viewer Screens',
        'Verify Support Ticket Creation & File Upload',
        'Verify Guest Mode Restricted Access Block',
        'Verify User Logout & Local Database Clearing',
        'Verify Login Screen Re-entry After Logout',
        'Verify Expired Session Token Auto-Refresh',
        'Verify Concurrent Record Edits Resolution',
        'Verify Database Migration Data Integrity Check',
        'Verify Push Notification Tap Deep Link Route',
        'Verify High Contrast Accessibility Mode Support',
        'Verify Screen Reader TalkBack Labels Correctness',
        'Verify Form Input Max Characters Edge Cases',
        'Verify Special Characters Unicode Handling',
        'Verify Rapid Repeated Button Double Tap Guard',
        'Verify Low Storage Space File Save Alert',
        'Verify Firebase Analytics Event Dispatch Check',
        'Verify Crashlytics Error Logging Handshake',
        'Verify HealthLog Full End-to-End Regression Test'
      ]
    }
  ];

  return categories;
}

module.exports = {
  getCategoryTestDefinitions
};
